project_id = "fisjgmjnezcchxnhihxc"

[functions.exchange-rates]
verify_jwt = false

[functions.moneroo-checkout]
verify_jwt = false

[functions.moneroo-webhook]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.api-sales]
verify_jwt = false

[functions.api-clients]
verify_jwt = false
